ALTER TYPE "AuditTargetType" ADD VALUE IF NOT EXISTS 'GENERATION';
ALTER TYPE "AuditActionType" ADD VALUE IF NOT EXISTS 'AI_GENERATION_DRAFTED';
ALTER TYPE "AuditActionType" ADD VALUE IF NOT EXISTS 'AI_GENERATION_REJECTED';
ALTER TYPE "AuditActionType" ADD VALUE IF NOT EXISTS 'AI_GENERATION_PUBLISHED';
