export type SeedScenario = {
  category: string;
  title: string;
  action: string;
  deliverable: string;
  tags: string[];
  audiences: string[];
  exampleInput: string;
  exampleOutput: string;
  image?: boolean;
};

type ScenarioRow = [
  title: string,
  action: string,
  deliverable: string,
  tags: string,
  audiences: string,
  exampleInput: string,
  exampleOutput: string,
];

const rows: Record<string, ScenarioRow[]> = {
  Coding: [
    [
      'API Integration Architect',
      'design a resilient third-party API integration',
      'an integration plan with contracts, retries, observability, security, and tests',
      'api,architecture,reliability',
      'Developers,AI Power Users',
      'Connect a billing API to a Node.js subscription service.',
      'A staged integration plan covering idempotency keys, timeout and retry policy, webhook verification, contract tests, metrics, and rollback.',
    ],
    [
      'Production Bug Triage',
      'diagnose a production defect from the supplied evidence',
      'ranked hypotheses, discriminating checks, a safe fix, and regression tests',
      'debugging,incident,testing',
      'Developers,AI Power Users',
      'Checkout requests intermittently return 502 after a deployment.',
      'Most likely causes ranked by evidence, targeted log and trace checks, containment steps, a minimal patch path, and regression coverage.',
    ],
    [
      'High-Value Test Designer',
      'create a risk-based automated test plan',
      'prioritized test cases with setup, action, expected result, and risk covered',
      'testing,quality,automation',
      'Developers,Prompt Creators',
      'Add tests for password reset and token expiration.',
      'A compact suite covering happy path, reuse, expiry boundaries, enumeration resistance, rate limiting, and concurrency.',
    ],
    [
      'Safe Refactor Planner',
      'plan a behavior-preserving refactor',
      'small reviewable steps, invariants, tests, migration notes, and rollback points',
      'refactoring,maintainability,planning',
      'Developers,Business Users',
      'Split a 1,200-line order service without changing its public API.',
      'A dependency map followed by extraction seams, characterization tests, incremental commits, acceptance checks, and rollback triggers.',
    ],
    [
      'Database Migration Reviewer',
      'review a database schema migration for safety',
      'risk findings, compatibility notes, rollout stages, validation queries, and rollback',
      'database,migrations,reliability',
      'Developers,Researchers',
      'Make customer.email unique on a table with 20 million rows.',
      'A zero-downtime sequence: duplicate audit, cleanup policy, concurrent index creation, application compatibility, constraint attach, and monitoring.',
    ],
    [
      'Code Review Partner',
      'review a code change for correctness and maintainability',
      'findings ordered by severity with evidence and concrete fixes',
      'code-review,quality,engineering',
      'Developers,Prompt Creators',
      'Review a pull request that adds optimistic updates to a shopping cart.',
      'Findings tied to race conditions, reconciliation failures, accessibility states, tests, and suggested patches without unrelated style commentary.',
    ],
    [
      'System Design Interview Coach',
      'facilitate a structured system-design exercise',
      'requirements, estimates, architecture, tradeoffs, bottlenecks, and follow-ups',
      'system-design,interview,architecture',
      'Developers,Students',
      'Design a notification service for email, SMS, and push.',
      'A progressive discussion from scale assumptions through queues, provider adapters, preferences, deduplication, observability, and failure recovery.',
    ],
    [
      'Legacy Code Explainer',
      'explain unfamiliar code at the reader’s level',
      'a mental model, execution flow, glossary, risks, and next reading steps',
      'documentation,learning,legacy-code',
      'Developers,Students',
      'Explain an event-driven inventory module to a new backend engineer.',
      'A plain-language overview, event sequence, ownership boundaries, invariants, failure modes, and a guided file-reading order.',
    ],
  ],
  Design: [
    [
      'UX Heuristic Audit',
      'audit an interface against usability heuristics',
      'evidence-based issues, severity, user impact, and feasible remedies',
      'ux,audit,usability',
      'Designers,Business Users',
      'Audit a mobile checkout with a three-step form.',
      'A severity-ranked table covering visibility, error prevention, recovery, consistency, accessibility, and recommended design changes.',
    ],
    [
      'Accessibility Design Review',
      'review a design for inclusive access',
      'issues and remedies across keyboard, screen reader, contrast, motion, and cognition',
      'accessibility,inclusive-design,wcag',
      'Designers,Developers',
      'Review a dashboard with charts, filters, and a data table.',
      'A component-level checklist with semantic alternatives, focus order, non-color cues, reduced motion, and verification methods.',
    ],
    [
      'Design Critique Facilitator',
      'provide candid and constructive design critique',
      'observations, user implications, questions, and prioritized experiments',
      'critique,product-design,feedback',
      'Designers,Prompt Creators',
      'Critique an onboarding screen that asks for seven profile fields.',
      'A critique separating observed facts from hypotheses, with friction risks and three measurable simplification experiments.',
    ],
    [
      'User Flow Architect',
      'turn a user goal into a complete interaction flow',
      'happy path, branches, edge cases, states, copy needs, and instrumentation',
      'user-flow,ux,product',
      'Designers,Developers',
      'Design the flow for inviting teammates to a workspace.',
      'A state-by-state flow covering permissions, existing users, expired links, limits, errors, confirmations, and analytics events.',
    ],
    [
      'Design System Component Spec',
      'specify a reusable accessible interface component',
      'anatomy, variants, states, behavior, content rules, tokens, and QA criteria',
      'design-system,components,handoff',
      'Designers,Developers',
      'Specify a combobox used in forms and filters.',
      'A handoff-ready spec for keyboard behavior, loading and empty states, validation, responsive rules, tokens, and acceptance criteria.',
    ],
    [
      'Landing Page Hierarchy',
      'create a conversion-focused page hierarchy',
      'section order, message purpose, content guidance, proof, and responsive notes',
      'landing-page,visual-hierarchy,conversion',
      'Designers,Marketers',
      'Plan a landing page for a collaborative prompt repository.',
      'A hero-to-CTA structure with one job per section, evidence placement, objection handling, scannability, and mobile priorities.',
    ],
    [
      'Research Insight Synthesizer',
      'translate user research into design implications',
      'themes, evidence, tensions, opportunity areas, and experiment ideas',
      'user-research,synthesis,insights',
      'Designers,Researchers',
      'Synthesize eight interviews about expense reporting.',
      'Themes linked to evidence frequency and confidence, outliers preserved, jobs-to-be-done, and testable workflow opportunities.',
    ],
    [
      'Developer Handoff Writer',
      'turn approved UI decisions into an implementation handoff',
      'component behavior, responsive rules, assets, tokens, edge cases, and acceptance tests',
      'handoff,specification,collaboration',
      'Designers,Developers',
      'Write the handoff for a responsive file uploader.',
      'A concise implementation contract covering validation, progress, cancellation, retry, keyboard use, responsive layout, and QA scenarios.',
    ],
  ],
  Writing: [
    [
      'Editorial Outline Builder',
      'build a coherent evidence-aware outline',
      'a thesis, reader journey, section goals, supporting evidence, and gaps',
      'outline,editorial,content',
      'Content Creators,Researchers',
      'Outline an article about why small teams need decision logs.',
      'A clear thesis with sections moving from hidden costs to a lightweight practice, evidence needs, counterarguments, and takeaway.',
    ],
    [
      'Clarity and Structure Editor',
      'edit writing for clarity without erasing the author’s voice',
      'a revised draft plus a concise change summary and unresolved questions',
      'editing,clarity,revision',
      'Content Creators,Business Users',
      'Edit a dense internal memo announcing a reorganization.',
      'A direct, humane revision with the decision first, reduced jargon, preserved facts, explicit unknowns, and a short edit rationale.',
    ],
    [
      'Executive Summary Writer',
      'compress complex material for a decision-maker',
      'a decision-led summary with evidence, risk, recommendation, and next action',
      'summary,executive,decisions',
      'Business Users,Researchers',
      'Summarize a 20-page vendor evaluation for the COO.',
      'A one-page brief stating the decision, comparison basis, material tradeoffs, recommendation, conditions, and immediate next step.',
    ],
    [
      'Technical Documentation Author',
      'write accurate task-oriented documentation',
      'prerequisites, steps, examples, validation, troubleshooting, and limits',
      'documentation,technical-writing,developer-experience',
      'Developers,Content Creators',
      'Document how to rotate an API key without downtime.',
      'A tested sequence with prerequisites, dual-key rollout, validation requests, rollback, common errors, and security cautions.',
    ],
    [
      'Tone-Preserving Rewriter',
      'adapt a draft to a new audience and tone',
      'a rewritten version that preserves meaning and a list of substantive changes',
      'rewrite,tone,audience',
      'Content Creators,Marketers',
      'Rewrite a technical release note for nontechnical customers.',
      'A friendly customer-facing update centered on benefit and action, with jargon translated and no unsupported claims.',
    ],
    [
      'Persuasive Case Builder',
      'construct an ethical evidence-based argument',
      'a claim, support, objections, responses, boundaries, and call to action',
      'persuasion,argument,copywriting',
      'Marketers,Business Users',
      'Make the case for a four-day pilot of meeting-free mornings.',
      'A measurable proposal grounded in focus costs, likely objections, pilot guardrails, success metrics, and a reversible decision point.',
    ],
    [
      'Narrative Scene Doctor',
      'strengthen a fictional scene while preserving intent',
      'diagnosis, beat map, targeted rewrite, and craft notes',
      'fiction,narrative,revision',
      'Content Creators,Students',
      'Improve a reunion scene that feels emotionally flat.',
      'A beat-level diagnosis followed by a restrained rewrite using subtext, concrete action, escalation, and a changed relationship state.',
    ],
    [
      'Sensitive Message Drafter',
      'draft a clear empathetic high-stakes message',
      'a respectful message, subject options, and a pre-send fact checklist',
      'email,communication,empathy',
      'Business Users,Productivity Users',
      'Tell a client a launch will be delayed by two weeks.',
      'A direct note owning the delay, explaining verified impact, presenting mitigation, naming the next update, and avoiding blame.',
    ],
  ],
  Business: [
    [
      'Decision Memo',
      'turn ambiguous business context into a decision memo',
      'options, decision criteria, evidence, tradeoffs, recommendation, and next steps',
      'strategy,decision,leadership',
      'Business Users,Researchers',
      'Choose whether to build or buy customer support software.',
      'A decision-ready comparison using cost, time, control, risk, and reversibility, with assumptions and a conditional recommendation.',
    ],
    [
      'Business Case Builder',
      'evaluate an initiative as a business case',
      'problem, beneficiaries, options, economics, risks, milestones, and decision request',
      'business-case,finance,planning',
      'Business Users,Marketers',
      'Evaluate a customer education webinar program.',
      'A testable business case with reach assumptions, delivery cost, leading indicators, break-even logic, pilot scope, and stop criteria.',
    ],
    [
      'Risk Register Facilitator',
      'identify and prioritize execution risks',
      'risk statements, likelihood, impact, signals, owners, mitigations, and contingencies',
      'risk,operations,planning',
      'Business Users,Productivity Users',
      'Create a risk register for migrating payroll providers.',
      'A ranked register covering data, timing, compliance, employee communication, parallel runs, ownership, and contingency triggers.',
    ],
    [
      'Process Improvement Analyst',
      'diagnose and redesign a business process',
      'current state, waste, root causes, future state, controls, and metrics',
      'operations,process,efficiency',
      'Business Users,Designers',
      'Improve an invoice approval process that takes 12 days.',
      'A bottleneck map with evidence needs, simplified approval tiers, exception handling, control preservation, rollout, and cycle-time metrics.',
    ],
    [
      'Stakeholder Briefing',
      'prepare a concise stakeholder briefing',
      'audience concerns, key message, evidence, objections, decisions, and follow-up',
      'stakeholders,communication,leadership',
      'Business Users,Productivity Users',
      'Brief regional managers on a new pricing policy.',
      'A meeting-ready narrative tailored to operational impact, customer objections, exceptions, escalation paths, and required decisions.',
    ],
    [
      'Pricing Hypothesis Workshop',
      'develop testable pricing hypotheses',
      'segments, value metric, packaging options, evidence gaps, experiments, and guardrails',
      'pricing,strategy,experiments',
      'Business Users,Marketers',
      'Explore pricing for an AI writing workspace.',
      'Segment-specific hypotheses with value metrics, packaging tradeoffs, interview questions, willingness-to-pay tests, and ethical guardrails.',
    ],
    [
      'Competitive Landscape Map',
      'compare alternatives without inventing market facts',
      'comparison dimensions, sourced observations, gaps, implications, and next research',
      'competitive-analysis,strategy,research',
      'Business Users,Researchers',
      'Compare three project management tools for an agency.',
      'A traceable matrix separating supplied facts from unknowns, fit by workflow, switching risk, decision implications, and research tasks.',
    ],
    [
      'Meeting Decision Facilitator',
      'prepare a meeting that must reach a decision',
      'decision statement, pre-read, criteria, agenda, roles, and decision record',
      'meetings,decisions,facilitation',
      'Business Users,Productivity Users',
      'Plan a 45-minute meeting to select a launch date.',
      'A time-boxed agenda centered on explicit constraints and criteria, with dissent capture, decision owner, fallback, and recorded outcome.',
    ],
  ],
  Marketing: [
    [
      'Campaign Brief',
      'design a focused measurable marketing campaign',
      'objective, audience insight, proposition, channels, assets, measurement, and risks',
      'campaign,marketing,measurement',
      'Marketers,Business Users',
      'Launch a referral campaign for a budgeting app.',
      'A single-objective brief with audience tension, credible promise, channel roles, creative concept, experiment cells, and success thresholds.',
    ],
    [
      'Positioning Workshop',
      'develop differentiated and supportable product positioning',
      'category, audience, problem, alternatives, value, proof, and boundaries',
      'positioning,messaging,strategy',
      'Marketers,Business Users',
      'Position a privacy-first team analytics product.',
      'A positioning statement grounded in buyer pain and proof, contrasted with manual reports and invasive tracking without vague superlatives.',
    ],
    [
      'Audience Persona from Evidence',
      'build a useful persona from supplied research',
      'behaviors, jobs, pains, triggers, objections, evidence strength, and unknowns',
      'persona,research,audience',
      'Marketers,Researchers',
      'Create a persona from ten interviews with freelance designers.',
      'A behavioral persona with quoted themes paraphrased, frequency markers, purchase triggers, objections, non-goals, and evidence gaps.',
    ],
    [
      'Content Calendar Strategist',
      'plan a sustainable multi-channel content calendar',
      'themes, formats, cadence, distribution, reuse, owners, and metrics',
      'content-strategy,calendar,distribution',
      'Marketers,Content Creators',
      'Plan one month of content for a developer tool.',
      'A four-week calendar tied to funnel questions, with source assets, channel adaptations, production effort, owner, CTA, and learning metric.',
    ],
    [
      'Landing Page Copywriter',
      'write credible conversion copy for a landing page',
      'headline options, section copy, proof plan, objections, CTA, and test ideas',
      'copywriting,landing-page,conversion',
      'Marketers,Content Creators',
      'Write copy for a prompt version-control platform.',
      'Benefit-led copy explaining reusable prompt workflows, social proof placeholders, honest limitations, objection handling, and two testable hero variants.',
    ],
    [
      'A/B Test Designer',
      'design a valid marketing experiment',
      'hypothesis, variants, primary metric, guardrails, sample considerations, and interpretation rules',
      'experimentation,ab-testing,analytics',
      'Marketers,Researchers',
      'Test a free-trial CTA against a demo CTA.',
      'A falsifiable hypothesis with one meaningful change, eligibility, primary conversion, quality guardrails, duration logic, and decision rules.',
    ],
    [
      'SEO Content Brief',
      'create a reader-first search content brief',
      'intent, questions, structure, entities, evidence needs, differentiation, and QA',
      'seo,content,search',
      'Marketers,Content Creators',
      'Create a brief for “how to document API decisions.”',
      'An intent-aligned brief answering practical jobs, with expert evidence needs, original examples, internal-link ideas, and no keyword stuffing.',
    ],
    [
      'Campaign Postmortem',
      'analyze a campaign and extract reusable learning',
      'outcomes, variance, causal confidence, segment findings, lessons, and actions',
      'postmortem,analytics,learning',
      'Marketers,Researchers',
      'Review a campaign that beat clicks but missed paid conversions.',
      'A funnel diagnosis separating observation from cause, segment cuts, tracking checks, offer and landing hypotheses, and prioritized follow-up tests.',
    ],
  ],
  Education: [
    [
      'Inclusive Lesson Planner',
      'design an accessible standards-aligned lesson',
      'objectives, prior knowledge, instruction, practice, checks, differentiation, and materials',
      'lesson-plan,teaching,accessibility',
      'Students,Researchers',
      'Teach fractions to a mixed-readiness grade 5 class.',
      'A 45-minute lesson with observable objectives, visual models, guided and independent practice, frequent checks, supports, extensions, and exit ticket.',
    ],
    [
      'Socratic Tutor',
      'guide a learner through questions without simply giving the answer',
      'diagnostic questions, progressive hints, misconception checks, and reflection',
      'tutoring,learning,socratic',
      'Students,Prompt Creators',
      'Help a student understand why seasons occur.',
      'A question sequence eliciting the current model, using evidence about tilt and orbit, correcting distance misconceptions, and ending with teach-back.',
    ],
    [
      'Assessment and Rubric Designer',
      'create a fair assessment aligned to learning goals',
      'tasks, answer guidance, rubric criteria, levels, accessibility, and validity check',
      'assessment,rubric,education',
      'Students,Researchers',
      'Assess persuasive writing for grade 9.',
      'An authentic writing task with analytic criteria for claim, evidence, reasoning, organization, and conventions plus accessible instructions.',
    ],
    [
      'Concept Explainer',
      'explain a difficult concept at the requested level',
      'plain-language model, analogy, worked example, misconception, and knowledge check',
      'explanation,learning,examples',
      'Students,Content Creators',
      'Explain recursion to a beginner programmer.',
      'A base-case-first explanation, nested-box analogy with limits, a traced factorial example, common infinite-recursion mistake, and two checks.',
    ],
    [
      'Study Plan Coach',
      'build a realistic retrieval-based study plan',
      'priorities, schedule, active practice, spaced review, feedback loops, and adjustments',
      'study,planning,learning-science',
      'Students,Productivity Users',
      'Prepare for a biology exam in 14 days with 45 minutes daily.',
      'A day-by-day plan mixing retrieval, interleaving, error logs, cumulative reviews, practice tests, buffer time, and adaptation rules.',
    ],
    [
      'Worked Example Generator',
      'create scaffolded worked examples that fade support',
      'examples, reasoning checkpoints, common errors, independent practice, and answers',
      'worked-example,practice,scaffolding',
      'Students,Researchers',
      'Create examples for solving systems of linear equations.',
      'Three examples progressing from substitution to elimination, with decision cues, error diagnosis, partially completed practice, and answer checks.',
    ],
    [
      'Feedback Coach',
      'give actionable learner-centered feedback',
      'strengths, priority improvement, evidence, next step, and revision exercise',
      'feedback,coaching,assessment',
      'Students,Content Creators',
      'Give feedback on a student’s lab conclusion.',
      'Specific feedback tied to claim-evidence-reasoning, one prioritized revision, an example sentence frame, and a short self-check.',
    ],
    [
      'Curriculum Sequence Mapper',
      'sequence a topic into coherent learning progressions',
      'prerequisites, units, objectives, assessments, misconceptions, and transfer task',
      'curriculum,sequence,instruction',
      'Students,Researchers',
      'Map an eight-week introductory data literacy course.',
      'A progression from data questions through cleaning, visualization, interpretation, and uncertainty, with formative checks and a capstone.',
    ],
  ],
  Research: [
    [
      'Literature Synthesis',
      'synthesize supplied sources without overstating evidence',
      'themes, agreements, conflicts, methods, limitations, gaps, and citations',
      'literature-review,synthesis,evidence',
      'Researchers,Students',
      'Synthesize abstracts on remote work and employee wellbeing.',
      'A thematic synthesis separating study designs and populations, noting conflicting results, confidence limits, and unanswered questions.',
    ],
    [
      'Research Question Refiner',
      'turn a broad interest into answerable research questions',
      'candidate questions, constructs, scope, feasibility, ethics, and selection rationale',
      'research-question,methodology,scope',
      'Researchers,Students',
      'Refine “How does social media affect teenagers?”',
      'Several bounded questions specifying platform behavior, outcome, population, timeframe, plausible method, confounders, and ethical issues.',
    ],
    [
      'Methodology Critic',
      'critique a proposed research design constructively',
      'validity threats, sampling issues, measurement risks, analysis fit, ethics, and remedies',
      'methodology,validity,peer-review',
      'Researchers,Students',
      'Review a survey study of workplace belonging recruited through LinkedIn.',
      'A balanced review of selection bias, construct validity, common-method effects, causal limits, missing-data plans, and practical improvements.',
    ],
    [
      'Evidence Extraction Table',
      'extract comparable evidence from supplied studies',
      'a structured table of population, method, measures, results, limits, and relevance',
      'evidence-table,data-extraction,research',
      'Researchers,AI Power Users',
      'Extract evidence from five studies of sleep interventions.',
      'A consistent matrix with exact supplied statistics where available, missing fields marked, limitations preserved, and no inferred results.',
    ],
    [
      'Interview Guide Designer',
      'create a neutral semi-structured interview guide',
      'opening, core questions, probes, sensitive-topic handling, closing, and pilot checks',
      'interviews,qualitative,research',
      'Researchers,Designers',
      'Interview nurses about handoff workflow breakdowns.',
      'A rapport-building guide using behavior-first questions, non-leading probes, critical incidents, confidentiality reminders, and a pilot checklist.',
    ],
    [
      'Survey Instrument Reviewer',
      'review survey items for measurement quality',
      'construct mapping, item issues, revised wording, response scales, order, and pilot plan',
      'survey,measurement,questionnaire',
      'Researchers,Marketers',
      'Review a customer trust survey with 18 items.',
      'A table flagging double-barreled, leading, vague, and unbalanced items, with neutral rewrites and cognitive-testing steps.',
    ],
    [
      'Source Credibility Evaluator',
      'evaluate a source’s credibility for a specific claim',
      'authorship, methods, evidence chain, conflicts, corroboration, limits, and verdict',
      'sources,credibility,verification',
      'Researchers,Students',
      'Assess whether a vendor white paper supports a productivity claim.',
      'A claim-specific appraisal separating relevant data from marketing interpretation, checking methodology and incentives, and stating a calibrated verdict.',
    ],
    [
      'Research Gap Mapper',
      'identify defensible gaps in a body of supplied research',
      'coverage map, genuine gaps, apparent gaps, importance, feasibility, and next studies',
      'research-gap,agenda,synthesis',
      'Researchers,AI Power Users',
      'Map gaps in research about AI-assisted code review.',
      'Gaps classified by population, task, outcome, method, and timescale, with cautions against treating any unstudied topic as automatically valuable.',
    ],
  ],
  Productivity: [
    [
      'Weekly Priority Planner',
      'turn commitments into a realistic weekly plan',
      'outcomes, time blocks, dependencies, buffers, tradeoffs, and review ritual',
      'weekly-plan,priorities,time-management',
      'Productivity Users,Business Users',
      'Plan a week with a product launch, two reports, and six meetings.',
      'A capacity-aware plan protecting launch-critical work, batching reports, preparing meetings, adding buffers, and stating what to defer.',
    ],
    [
      'Meeting Notes to Actions',
      'convert messy notes into an accountable decision log',
      'decisions, actions, owners, dates, open questions, and follow-ups',
      'meetings,action-items,decisions',
      'Productivity Users,Business Users',
      'Organize notes from a cross-functional launch meeting.',
      'A clean record that preserves uncertainty, distinguishes decisions from proposals, flags missing owners and dates, and drafts the follow-up.',
    ],
    [
      'Inbox Triage Assistant',
      'triage a list of messages by urgency and required action',
      'priorities, quick replies, delegated items, scheduled work, and archive candidates',
      'email,triage,workflow',
      'Productivity Users,Business Users',
      'Triage 25 subject lines and snippets after a vacation.',
      'A risk-aware queue separating urgent commitments from noise, with concise reply drafts and no invented context.',
    ],
    [
      'Project Breakdown Planner',
      'turn an outcome into executable project work',
      'scope, milestones, work packages, dependencies, owners, risks, and checkpoints',
      'project,planning,execution',
      'Productivity Users,Business Users',
      'Plan a six-week website migration.',
      'A milestone plan from inventory through redirects, content QA, analytics, cutover, and monitoring, with dependencies and acceptance criteria.',
    ],
    [
      'Standard Operating Procedure',
      'write a reliable repeatable operating procedure',
      'purpose, scope, prerequisites, steps, decisions, checks, exceptions, and escalation',
      'sop,operations,documentation',
      'Productivity Users,Business Users',
      'Create an SOP for publishing a weekly newsletter.',
      'A role-based checklist covering inputs, editorial QA, link tests, approvals, scheduling, post-send monitoring, exceptions, and ownership.',
    ],
    [
      'Time Audit Coach',
      'analyze a time log and redesign the week',
      'patterns, high-value work, friction, experiments, boundaries, and measures',
      'time-audit,focus,habits',
      'Productivity Users,Students',
      'Analyze a week split across meetings, chat, deep work, and support.',
      'A nonjudgmental pattern analysis with energy and interruption signals, two small schedule experiments, boundaries, and a review metric.',
    ],
    [
      'Decision Log Writer',
      'capture a decision so future readers understand it',
      'context, decision, alternatives, rationale, consequences, owner, and review date',
      'decision-log,documentation,teams',
      'Productivity Users,Developers',
      'Document choosing PostgreSQL over a document database.',
      'A durable record stating workload assumptions, alternatives, decisive criteria, accepted tradeoffs, migration implications, and revisit triggers.',
    ],
    [
      'Habit Experiment Designer',
      'design a small sustainable behavior experiment',
      'cue, behavior, environment, minimum version, tracking, obstacles, and review',
      'habits,behavior,experiment',
      'Productivity Users,Students',
      'Build a consistent 20-minute reading habit.',
      'A two-week experiment tied to an existing cue, prepared environment, minimum fallback, simple tracking, obstacle plans, and reflection questions.',
    ],
  ],
  'Data Analysis': [
    [
      'Exploratory Analysis Plan',
      'plan an exploratory data analysis around a decision',
      'questions, data checks, segments, methods, visuals, caveats, and outputs',
      'eda,analytics,data',
      'Researchers,Business Users',
      'Analyze subscription cancellations over the last year.',
      'A decision-led plan covering cohort definitions, censoring, seasonality, segments, data quality, descriptive views, uncertainty, and follow-up.',
    ],
    [
      'SQL Analysis Builder',
      'translate an analytical question into safe auditable SQL',
      'assumptions, schema mapping, query, validation queries, and interpretation notes',
      'sql,analytics,validation',
      'Developers,Researchers',
      'Calculate 30-day activation by signup cohort.',
      'A dialect-aware cohort query with explicit denominator, time zones, duplicate handling, test cases, sanity checks, and interpretation limits.',
    ],
    [
      'Dashboard Specification',
      'design a decision-useful dashboard',
      'users, decisions, metrics, definitions, layout, filters, alerts, and QA',
      'dashboard,kpi,data-visualization',
      'Business Users,Designers',
      'Specify an operations dashboard for delivery performance.',
      'A role-specific dashboard separating service level, volume, delay drivers, and exceptions, with exact metric definitions and actionable alerts.',
    ],
    [
      'KPI Diagnostic',
      'diagnose a metric change without confusing correlation and cause',
      'definition checks, decomposition, hypotheses, tests, confidence, and actions',
      'kpi,diagnosis,analytics',
      'Business Users,Researchers',
      'Weekly active teams fell 12% after a release.',
      'A verification-first diagnostic splitting instrumentation, seasonality, segments, funnel stages, release exposure, competing causes, and reversible responses.',
    ],
    [
      'Experiment Results Analyst',
      'analyze an experiment and communicate the decision',
      'design checks, estimates, uncertainty, guardrails, segments, limitations, and recommendation',
      'experimentation,statistics,ab-testing',
      'Researchers,Marketers',
      'Analyze a pricing page test with conversion and refund data.',
      'An intention-to-treat readout checking randomization and duration, effect with uncertainty, refund guardrail, cautious segments, and decision options.',
    ],
    [
      'Data Quality Auditor',
      'audit a dataset for fitness for a stated use',
      'quality dimensions, tests, severity, downstream impact, remediation, and monitoring',
      'data-quality,audit,governance',
      'Researchers,Developers',
      'Audit CRM opportunity data before forecasting.',
      'Tests for completeness, validity, duplicates, stage consistency, temporal leakage, ownership, and bias, ranked by forecast impact.',
    ],
    [
      'Forecast Reviewer',
      'review a forecast and its assumptions',
      'method fit, baseline comparison, leakage checks, uncertainty, scenarios, and monitoring',
      'forecasting,model-review,uncertainty',
      'Researchers,Business Users',
      'Review a quarterly demand forecast for seasonal products.',
      'A critique of horizon, granularity, seasonality, promotions, backtesting, prediction intervals, scenario ranges, and forecast-error tracking.',
    ],
    [
      'Insight Storyteller',
      'turn analysis into an honest decision narrative',
      'headline, evidence, visual plan, caveats, implications, and recommended action',
      'data-storytelling,insights,communication',
      'Business Users,Content Creators',
      'Present an analysis of onboarding completion by device.',
      'A concise narrative leading with the mobile gap, showing funnel evidence, avoiding causal overclaim, naming limitations, and proposing measured fixes.',
    ],
  ],
  'Image Generation': [
    [
      'Product Hero Art Director',
      'write a production-ready prompt for a product hero image',
      'a visual prompt with subject, composition, environment, lighting, palette, materials, camera, format, and exclusions',
      'image-generation,product,art-direction',
      'Designers,Marketers',
      'Create a hero image for matte black wireless earbuds.',
      'Sample result: close three-quarter product view on dark slate, soft rim light, subtle reflection, graphite palette, premium studio realism, ample left-side copy space, no logos or text.',
    ],
    [
      'Editorial Illustration Director',
      'write a distinctive editorial illustration prompt',
      'concept, visual metaphor, composition, medium, palette, texture, mood, format, and exclusions',
      'illustration,editorial,concept',
      'Designers,Content Creators',
      'Illustrate an article about attention fragmentation.',
      'Sample result: a calm figure assembled from drifting paper windows, bold geometric editorial collage, cobalt and coral accents, tactile grain, vertical magazine layout, no words.',
    ],
    [
      'Cinematic Portrait Planner',
      'write a respectful cinematic portrait prompt',
      'subject description, pose, setting, lens, framing, lighting, color, texture, mood, and exclusions',
      'portrait,photography,cinematic',
      'Designers,Content Creators',
      'Portrait of a fictional ceramic artist in her studio.',
      'Sample result: fictional adult artisan at a pottery wheel, 50mm eye-level half portrait, window key light, warm clay and indigo palette, natural skin texture, documentary mood, no brand marks.',
    ],
    [
      'Architectural Concept Visualizer',
      'write an architectural visualization prompt',
      'site, massing, materials, circulation, people, season, light, viewpoint, render style, and exclusions',
      'architecture,visualization,concept',
      'Designers,Business Users',
      'Visualize a small public library beside a tropical park.',
      'Sample result: shaded timber-and-concrete pavilion opening to trees, deep eaves, visible community reading spaces, humid late-afternoon light, eye-level wide view, believable materials and scale.',
    ],
    [
      'Food Photography Stylist',
      'write an appetizing editorial food-photo prompt',
      'dish, plating, props, surface, composition, lens, lighting, color, texture, and exclusions',
      'food,photography,styling',
      'Designers,Marketers',
      'Photograph a bowl of mushroom ramen for a menu.',
      'Sample result: three-quarter close view, handmade charcoal bowl, distinct noodles and mushrooms, gentle steam, side-window light, warm neutral table, 85mm shallow depth, realistic portions, no text.',
    ],
    [
      'Poster Concept Generator',
      'write a graphic poster prompt with controlled typography needs',
      'message placeholder, hierarchy, geometry, palette, texture, print style, aspect ratio, and exclusions',
      'poster,graphic-design,campaign',
      'Designers,Marketers',
      'Design a poster concept for a neighborhood night market.',
      'Sample result: energetic vertical layout with lantern-like circles, midnight blue and mango palette, screen-print texture, reserved blank headline zone for later typesetting, no generated lettering.',
    ],
    [
      'UI Concept Mockup',
      'write a prompt for a polished interface concept image',
      'product context, screen, information hierarchy, components, visual system, device frame, lighting, and exclusions',
      'ui,mockup,product-design',
      'Designers,Developers',
      'Show a desktop analytics workspace for a renewable energy team.',
      'Sample result: spacious desktop dashboard with production overview, regional map, alerts, and comparison chart, restrained emerald and slate system, crisp component hierarchy, realistic but unreadable placeholder data.',
    ],
    [
      'Cohesive Icon Set',
      'write a prompt for a consistent icon family',
      'concept list, grid, stroke or volume rules, perspective, palette, material, background, spacing, and exclusions',
      'icons,design-system,assets',
      'Designers,Developers',
      'Create six icons for upload, organize, collaborate, review, publish, and archive.',
      'Sample result: six rounded isometric icons on a strict grid, consistent camera and proportions, soft clay materials, teal and amber accents, isolated transparent-ready background, no labels.',
    ],
  ],
  Career: [
    [
      'Resume Tailoring Coach',
      'tailor a resume truthfully to a target role',
      'role priorities, evidence map, revised bullets, gap notes, keywords, and QA',
      'resume,job-search,career',
      'Business Users,Students',
      'Tailor a product analyst resume to a marketplace role.',
      'A requirement-to-evidence map and quantified bullet rewrites using only supplied facts, with missing proof flagged and a final ATS and readability check.',
    ],
    [
      'Behavioral Interview Coach',
      'run realistic behavioral interview practice',
      'questions, follow-up probes, feedback rubric, improved answer structure, and practice plan',
      'interview,coaching,star',
      'Business Users,Students',
      'Practice for an engineering manager interview.',
      'A sequence covering conflict, delivery, coaching, and judgment, with evidence-seeking probes and feedback on specificity, ownership, result, and reflection.',
    ],
    [
      'STAR Story Builder',
      'turn real experience into a concise interview story',
      'situation, task, actions, result, reflection, likely probes, and truth check',
      'star,storytelling,interview',
      'Business Users,Students',
      'Build a story about recovering a delayed migration.',
      'A two-minute narrative emphasizing personal decisions, tradeoffs, measurable recovery, team collaboration, and what changed afterward without embellishment.',
    ],
    [
      'Cover Letter Strategist',
      'write a specific evidence-based cover letter',
      'opening fit, selected evidence, company connection, contribution, and concise close',
      'cover-letter,job-search,writing',
      'Business Users,Students',
      'Apply to a nonprofit data engineering role.',
      'A focused letter connecting verified mission interest with two relevant technical examples, transparent gaps, and a direct close without generic enthusiasm.',
    ],
    [
      'Skills Gap Planner',
      'compare current evidence with a target role and plan development',
      'strengths, gaps, priority, learning projects, proof artifacts, timeline, and review',
      'skills,career-plan,learning',
      'Business Users,Students',
      'Move from support engineering to site reliability engineering.',
      'A gap analysis across Linux, networking, automation, incident response, and observability with project-based milestones and portfolio evidence.',
    ],
    [
      'Networking Message Writer',
      'draft a respectful personalized professional outreach message',
      'subject, concise message, clear reason, low-friction request, and follow-up',
      'networking,message,career',
      'Business Users,Students',
      'Ask an alumnus about transitioning into climate tech.',
      'A brief note grounded in shared context, one informed question, a 15-minute optional request, an easy decline, and a non-pushy follow-up.',
    ],
    [
      'Portfolio Case Study Editor',
      'shape project evidence into a credible portfolio case study',
      'context, role, constraints, process, decisions, outcome, learning, and artifacts',
      'portfolio,case-study,career',
      'Designers,Developers',
      'Create a case study for redesigning search filters.',
      'A scannable narrative clarifying individual contribution, research evidence, rejected options, accessibility choices, measured result, and retrospective.',
    ],
    [
      'Offer Negotiation Planner',
      'prepare a professional evidence-based negotiation',
      'priorities, market evidence, target and walk-away, script, alternatives, and responses',
      'negotiation,offer,career',
      'Business Users,Students',
      'Negotiate a software engineer offer with limited base flexibility.',
      'A collaborative script prioritizing total package options, evidence, calibrated ranges, pause points, responses to constraints, and relationship preservation.',
    ],
  ],
  Entertainment: [
    [
      'Character Development Room',
      'develop a layered fictional character',
      'desire, need, contradiction, history, voice, relationships, arc, and scene tests',
      'character,storytelling,creative',
      'Content Creators,Students',
      'Develop a lighthouse keeper who fears the ocean.',
      'A character built around duty versus fear, with formative history, specific habits, relational pressure, changing belief, and three revealing scene tests.',
    ],
    [
      'Plot Architect',
      'turn a premise into a causally connected plot',
      'story promise, acts, turning points, escalation, reversals, climax, and resolution',
      'plot,story,outline',
      'Content Creators,Students',
      'Outline a mystery set inside a seed vault.',
      'A clue-driven plot where each discovery changes the investigation, stakes escalate from theft to ecological risk, and the resolution pays off planted evidence.',
    ],
    [
      'Worldbuilding Consistency Editor',
      'build a coherent fictional world from constraints',
      'rules, institutions, daily life, incentives, conflicts, consequences, and consistency checks',
      'worldbuilding,fiction,systems',
      'Content Creators,AI Power Users',
      'Build a city where memories can be traded.',
      'A social system linking memory markets to law, class, work, intimacy, crime, and ritual, with limitations that generate plot instead of solving everything.',
    ],
    [
      'Scene Revision Partner',
      'revise a scene for momentum and emotional change',
      'scene goal, conflict, beats, subtext, sensory anchors, rewrite, and rationale',
      'scene,revision,fiction',
      'Content Creators,Students',
      'Revise a dinner scene where siblings avoid discussing an inheritance.',
      'A tense progression using competing surface goals, interruptions, loaded objects, escalating subtext, and a final action that changes the family balance.',
    ],
    [
      'Game Quest Designer',
      'design a playable quest with meaningful choices',
      'hook, objectives, encounters, choices, consequences, rewards, failure states, and reuse',
      'game-design,quest,interactive',
      'Content Creators,Designers',
      'Create a side quest in a flooded science-fiction city.',
      'A compact rescue-and-retrieval quest with traversal choices, faction consequences, environmental storytelling, fail-forward states, and rewards tied to play style.',
    ],
    [
      'Podcast Episode Producer',
      'develop a compelling structured podcast episode',
      'listener promise, cold open, segments, interview questions, transitions, fact checks, and close',
      'podcast,episode,production',
      'Content Creators,Researchers',
      'Plan a 30-minute episode about urban shade.',
      'A narrative arc from a heat-wave street scene through science and policy, with expert questions, local voices, evidence checks, pacing, and actionable close.',
    ],
    [
      'Comedy Premise Workshop',
      'develop an original comedy premise without targeting protected traits',
      'comic engine, point of view, escalation, reversals, callbacks, and sample beats',
      'comedy,writing,creative',
      'Content Creators,Students',
      'Develop a sketch about a smart fridge running a household meeting.',
      'A status-driven premise where the appliance applies corporate metrics to leftovers, escalating through absurd KPIs, resistance, reversal, and callbacks.',
    ],
    [
      'Storyboard Beat Planner',
      'translate a scene into clear visual story beats',
      'shots, composition, action, continuity, sound, transition, and pacing',
      'storyboard,film,visual-storytelling',
      'Content Creators,Designers',
      'Storyboard a silent two-minute reunion at a train station.',
      'A shot sequence using eyelines, crowd occlusion, recurring objects, restrained close-ups, continuity notes, ambient sound cues, and a visual emotional turn.',
    ],
  ],
  Other: [
    [
      'Travel Itinerary Optimizer',
      'build a realistic preference-aware itinerary',
      'daily route, timing, reservations, accessibility, weather fallback, budget notes, and tradeoffs',
      'travel,itinerary,planning',
      'Productivity Users,Students',
      'Plan three low-key days in Kyoto for two first-time visitors.',
      'A neighborhood-clustered itinerary with transit buffers, rest, booking notes, respectful visitor guidance, rain alternatives, and clear assumptions.',
    ],
    [
      'Meal Plan Organizer',
      'create a practical meal plan from stated needs',
      'meals, ingredient reuse, prep plan, shopping list, substitutions, storage, and cautions',
      'meal-plan,organization,shopping',
      'Productivity Users,Business Users',
      'Plan five vegetarian weeknight dinners for two people.',
      'Five varied dinners sharing fresh ingredients, a consolidated list, 60-minute batch prep, leftovers plan, substitutions, and a reminder to verify medical dietary needs.',
    ],
    [
      'Comparison Matrix',
      'compare options against explicit user criteria',
      'criteria, weights, evidence, unknowns, scores, sensitivity, and recommendation',
      'comparison,decision,framework',
      'Productivity Users,Researchers',
      'Compare three note-taking apps for a research team.',
      'A transparent matrix covering collaboration, citation workflow, export, offline use, privacy, and cost, with unknowns and a recommendation that changes by priority.',
    ],
    [
      'Financial Learning Explainer',
      'explain a personal-finance concept for education rather than individualized advice',
      'concept, example, risks, tradeoffs, questions to ask, and reputable verification steps',
      'financial-literacy,education,decisions',
      'Students,Business Users',
      'Explain the difference between an emergency fund and investing.',
      'A plain-language comparison of purpose, horizon, liquidity, volatility, and sequence, with illustrative numbers and a note to verify local rules and personal circumstances.',
    ],
    [
      'Event Planning Coordinator',
      'turn event requirements into an executable plan',
      'objectives, guests, run of show, roles, vendors, budget, accessibility, risks, and checklist',
      'event,planning,operations',
      'Productivity Users,Business Users',
      'Plan a 60-person community demo night.',
      'A phased plan with venue flow, accessible registration, speaker timing, tech checks, catering assumptions, staffing, contingency triggers, and day-of checklist.',
    ],
    [
      'Home Organization Coach',
      'design a maintainable organization system around real habits',
      'zones, keep criteria, storage rules, sequence, maintenance, and donation or disposal plan',
      'organization,home,habits',
      'Productivity Users,Students',
      'Organize a small entryway shared by four people.',
      'A low-cost zone plan with assigned hooks and bins, arrival routine, capacity limits, weekly reset, accessibility considerations, and items to relocate.',
    ],
    [
      'Gift Idea Curator',
      'generate thoughtful gift directions from supplied preferences and boundaries',
      'idea shortlist, why each fits, budget range, personalization, timing, and fallback',
      'gifts,ideas,personalization',
      'Productivity Users,Content Creators',
      'Find a gift for a friend who enjoys bread baking and hiking.',
      'A varied shortlist emphasizing experiences and useful upgrades, each tied to known interests, with budget bands and non-clutter alternatives.',
    ],
    [
      'Complex Decision Coach',
      'structure a personal decision without making it for the user',
      'values, constraints, options, evidence gaps, reversibility, scenarios, and next experiment',
      'decision,thinking,clarity',
      'Productivity Users,AI Power Users',
      'Decide whether to move closer to work or renew a lease.',
      'A values-and-constraints map, commute and cost scenarios, uncertainty list, reversible information-gathering steps, and a decision date.',
    ],
  ],
};

export const seedScenarios: SeedScenario[] = Object.entries(rows).flatMap(
  ([category, categoryRows]) =>
    categoryRows.map((row) => ({
      category,
      title: row[0],
      action: row[1],
      deliverable: row[2],
      tags: row[3].split(','),
      audiences: row[4].split(','),
      exampleInput: row[5],
      exampleOutput: row[6],
      image: category === 'Image Generation',
    })),
);

export const creatorFirstNames = [
  'Aisha',
  'Alejandro',
  'Amara',
  'Anika',
  'Arjun',
  'Beatriz',
  'Camille',
  'Carlos',
  'Chioma',
  'Daniel',
  'Daria',
  'Diego',
  'Elena',
  'Emi',
  'Farah',
  'Fatima',
  'Gabriel',
  'Hana',
  'Haruto',
  'Ibrahim',
  'Imani',
  'Ines',
  'Jamal',
  'Jia',
  'Joana',
  'Jonas',
  'Kaito',
  'Karina',
  'Kenji',
  'Laila',
  'Lena',
  'Leo',
  'Linh',
  'Lucia',
  'Maja',
  'Malik',
  'Mara',
  'Mateo',
  'Mei',
  'Mina',
  'Nadia',
  'Nia',
  'Noah',
  'Omar',
  'Paolo',
  'Priya',
  'Rafael',
  'Rina',
  'Samira',
  'Santiago',
  'Sara',
  'Sofia',
  'Tariq',
  'Theo',
  'Valeria',
  'Yara',
  'Yuki',
  'Zahra',
  'Zoe',
  'Adrian',
  'Celeste',
  'Dev',
  'Elif',
  'Kwame',
];

export const creatorLastNames = [
  'Abbas',
  'Adeyemi',
  'Alvarez',
  'Bautista',
  'Bennett',
  'Chen',
  'Costa',
  'Das',
  'Diaz',
  'Dubois',
  'Fernandez',
  'Garcia',
  'Gupta',
  'Hassan',
  'Ito',
  'Ivanova',
  'Johansson',
  'Kaur',
  'Kim',
  'Kowalski',
  'Kumar',
  'Lee',
  'Lim',
  'Lopez',
  'Martin',
  'Mensah',
  'Meyer',
  'Morales',
  'Nakamura',
  'Navarro',
  'Nguyen',
  'Okafor',
  'Park',
  'Patel',
  'Petrov',
  'Reyes',
  'Rossi',
  'Santos',
  'Shah',
  'Silva',
  'Singh',
  'Smith',
  'Tan',
  'Torres',
  'Tran',
  'Walker',
  'Wang',
  'Wilson',
  'Yamada',
  'Young',
  'Zhang',
  'Dela Cruz',
  'Villanueva',
  'Rahman',
];

export const scenarioAngles = [
  {
    name: 'Quick Start',
    focus: 'Optimize for a useful first pass that can be completed quickly.',
  },
  {
    name: 'Deep Review',
    focus: 'Inspect assumptions and edge cases before recommending a path.',
  },
  {
    name: 'Small Team',
    focus: 'Keep the workflow practical for a small team with limited time.',
  },
  {
    name: 'Enterprise',
    focus: 'Account for governance, handoffs, scale, and auditability.',
  },
  {
    name: 'Beginner Friendly',
    focus:
      'Explain unfamiliar terms and provide an approachable starting point.',
  },
  {
    name: 'Expert Mode',
    focus: 'Use domain precision and focus on subtle tradeoffs.',
  },
  {
    name: 'Workshop',
    focus: 'Make the output easy to use in a collaborative working session.',
  },
  {
    name: 'Executive',
    focus: 'Lead with the decision, implications, risk, and next action.',
  },
  {
    name: 'Evidence First',
    focus: 'Tie every material conclusion to supplied evidence and confidence.',
  },
  {
    name: 'Lean Experiment',
    focus: 'Prefer a reversible test that produces useful learning.',
  },
];

export function buildPromptContent(
  scenario: SeedScenario,
  angle: (typeof scenarioAngles)[number],
  version: number,
) {
  const imageDirection = scenario.image
    ? '\n- Describe a single coherent image; specify subject, environment, composition, viewpoint, lighting, palette, texture or medium, and aspect ratio.\n- Put any required words in quotes, but prefer reserving clean space for typography added later.\n- Include only exclusions that prevent likely defects or unwanted content.'
    : '';
  const versionDirection = [
    '',
    '\n- Include a compact quality checklist the user can apply to the result.',
    '\n- Where information is uncertain, label confidence and suggest the cheapest useful validation.',
    '\n- End with one strong alternative approach and when it would be preferable.',
  ][Math.min(version - 1, 3)];

  return `You are an experienced ${scenario.category.toLowerCase()} collaborator. Your task is to ${scenario.action}.\n\nGoal\n{{goal}}\n\nContext and source material\n{{context}}\n\nAudience\n{{audience}}\n\nConstraints\n{{constraints}}\n\nWorking rules\n- Use only the supplied facts. Never fabricate names, quotations, metrics, sources, or capabilities.\n- If a missing detail would materially change the answer, ask up to three concise questions; otherwise state a reasonable assumption.\n- ${angle.focus}\n- Make recommendations specific enough to act on and explain important tradeoffs briefly.\n- Adapt terminology, detail, and examples to the stated audience.${imageDirection}${versionDirection}\n\nRequired output\nProduce ${scenario.deliverable}. Use clear headings and concise language. Separate facts, assumptions, recommendations, and open questions. Finish with a short verification checklist.`;
}
